### ISSUE TITLE
Request policy does not work any more with latest Seamonkey and Firefox builds due to internal changes in extension handling (new "WebExtensions" API with ceasing support of legacy extensions)

### ISSUE THREAD

**Issue by ChrisVienna** [RequestPolicyContinued/requestpolicy#851] opened 2017-09-27 11:39 UTC
- Browser: Seamonkey 2.54 since mid of August and latest build 2.55 and also Firefox since 57.a01 and latest build 58.a01
- RequestPolicy version: e.g. 1.0.beta13 

Request policy does not work any more with latest Seamonkey and Firefox builds due to internal changes in extension handling.
Mozilla only supports new "WebExtensions" API and is ceasing support of legacy extensions.
So RequestPolicy 1.0.beta13 does neither not show up its icon nor works any more.
RequestPolica 0.5 does show its icon and its configuration menu but nevertheless does not work any more.

Please make RequestPolicy work again and change over using the new Mozilla's WebExtension API.

Thanks in advance for your great work and improving online safety.

Best wishes,
Chris

**Comment by genodeftest** [comment] 2017-10-04 20:05
Duplicate of #704.

**Comment by myrdd** [comment] 2017-10-05 06:53
> Duplicate of #704.

correct

**Closed by myrdd** 2017-10-05 06:53 UTC
