### ISSUE TITLE
Blocked destination "null", requestlog shows dest="mediasource:https://www.youtube.com/..."

### ISSUE THREAD

**Issue by netjeff** [RequestPolicyContinued/requestpolicy#683] opened 2015-07-05 21:00 UTC
I've been troubleshooting some problems where YouTube is playing with Flash rather than the HTML5 player.  I've traced it down to this specific problem:

1. New clean profile in Firefox
2. View video on YouTube, correctly plays with HTML5 player (confirmed by right clicking on video)
3. Install RequestPolicyContinued v1.0beta10
4. Change "Default Policy" to "Block by default" with "Allow requests to same domain"
5. Disable all subscriptions
6. Try to play a YouTube video.  As expected, it fails because of block by default.
7. Using RequestPolicy menu, start adding rules one-at-a-time for "Allow request from *.youtube.com to *.foo.com"
8. Video now plays (including ads), but plays in Flash player not HTML5 player.

After repeating step 7 and adding rules, there is still a single Blocked Destination that says "null", see attached screenshot.  Trying to use the "Allow request from *.youtube.com to null" does not resolve it.  After trying, it still shows a Blocked Destination of "null". In the request log I can see a blocked destination of "mediasource:https://www.youtube.com/...", see attached.

Finally, if I create a rule for "Allow requests from *.youtube.com" to all destinations, nothing is blocked, and I get the YouTube HTML5 player.

So it is this "mediasource:..." destination that is confusing RequestPolicy, with no workaround other than allowing all requests from *.youtube.com.  I generally don't like "allow all from foo.com" rules, so hoping for a fix eventually.

![mediasource](https://cloud.githubusercontent.com/assets/3266932/8513376/1112c9b0-2326-11e5-93c2-88d87ca33bfd.jpg)

**Comment by nodiscc** [comment] 2015-07-06 17:01
Hi @netjeff, please check https://github.com/RequestPolicyContinued/requestpolicy/issues/619.

Is this a duplicate bug report?

**Comment by netjeff** [comment] 2015-07-06 21:48
@nodiscc: I suspect that mine and #619 will have the same root cause.  I see the #619 was originally logged for a menu entry "null" with underlying `rpc:\\`, followed by a comment from someone else seeing "null" with underlying `chrome-extension:\\`.  I discovered mine with "null" for underlying `mediasource:`.  So not totally identical, but probably will end up with same root cause.

**Comment by myrdd** [comment] 2015-07-08 20:15
duplicate of #626.

> You can work around this problem by manually adding a rule from  host `*.youtube.com` to destinations with scheme `mediasource`.

the main tracking issue is #619.

**Closed by myrdd** 2015-07-08 20:15 UTC
Labels: bug

**Comment by netjeff** [comment] 2015-07-09 06:43
Yup, the workaround works, so I don't need a general "allow all destinations from *.youtube.com rule.  Sweet.
