### ISSUE TITLE
RequestPolicy 1.0.0b3 and KeeFox 1.3.1 conflict

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#427] opened 2014-07-07 00:37 UTC
<a href="https://github.com/Hanatarou"><img src="https://avatars.githubusercontent.com/u/7038607?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hanatarou](https://github.com/Hanatarou)**
_Sunday Mar 23, 2014 at 14:33 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/427_

----

Hello folks,

I would like to report that there is a conflict between RequestPolicy 1.0.0b3 and KeeFox 1.3.1 that prevents KeeFox 1.3.1 from communicating with KeePass password database.

I have updated my KeeFox add-on to version 1.3.1 and after that I am experiencing difficulties to connect to KeePass database using Palemoon version 24.4.1 (x86). I am using KeePass version 2.25 and my OS is Windows 7 x64.

I keep receiving the following message: "KeeFox can not connect to KeePass. A firewall is probably blocking communication on TCP port 12546."

I have disabled one by one my add-ons and found out that the problematic one is RequestPolicy 1.0.0b3. It's blocking KeeFox 1.3.1 from communicating and just after I disable RequestPolicy 1.0.0b3 KeeFox 1.3.1 started working as expected.

I hope it helps debugging the issue.

Best regards,

Hanatarou

**Comment by mithrial** [comment] 2015-01-07 11:16
As a workaround I added the following rule for the target:
* Scheme: ws
* Host: 127.0.0.1
* Port: 12546 _(default port, look yours up in settings)_

**Comment by Radagast** [comment] 2015-04-07 22:26
I commented in the wrong place earlier - [RequestPolicy 1.0.0b3 and KeeFox 1.3.1 conflict #427](https://github.com/RequestPolicy/requestpolicy/issues/427) I should also mention, the problem only seems to manifest in default deny mode.

**Comment by Radagast** [comment] 2015-04-08 21:37
The rule mentioned above works for me, so maybe something like this needs to be added to the default set...

**Comment by Sec42** [comment] 2015-12-02 23:28
I just stumbled upon this problem. I had to whitelist scheme *, Host 127.0.0.1, Port 12546 for KeeFox to work.
I feel that allowing all pages to connect to my local socket might be a bad idea, though. So is there a way to limit it to the "about:blank" page that the request is coming from?

**Comment by Sec42** [comment] 2015-12-02 23:37
Ok, small update. It seems that specifying scheme "resource" as origin works, and I think this should improve security. Still maybe this should be enabled by default.

**Comment by myrdd** [comment] 2015-12-03 10:53
> I had to whitelist scheme *, Host 127.0.0.1, Port 12546 for KeeFox to work.

Didn't `ws` as scheme work?

> is there a way to limit it to the "about:blank" page that the request is coming from?

Not completely, paths are not supported yet, see #299, but you can add a rule with origin scheme "about".

> It seems that specifying scheme "resource" as origin works, and I think this should improve security.

I'll try that for a fix. Usually you should see the full URIs in the request log.

**Comment by Sec42** [comment] 2015-12-06 16:49
Hi,

On Thu, Dec 03, 2015 at 02:53 -0800, Martin Kimmerle wrote:
> > I had to whitelist scheme *, Host 127.0.0.1, Port 12546 for KeeFox to work.
> 
> Didn't `ws` as scheme work?

It did. Turns out I made a typo and typed "wc" instead...

> > It seems that specifying scheme "resource" as origin works, and I think this should improve security.
> 
> I'll try that for a fix. Usually you should see the full URIs in the request log.

scheme "resource" worked fine. Giving the fulll path in the "host" field
did not work.

CU,
    Sec
-- 
When in doubt, invent a chinese proverb.

**Comment by myrdd** [comment] 2015-12-06 19:54
The issue is fixed in v1.0.beta11pre2. @Sec42 please confirm that KeeFox works without a user-defined rule.

**Closed by myrdd** 2015-12-06 19:54 UTC
Labels: easy, extension conflict
