### ISSUE TITLE
Clicking the toolbar button should close the menu when it's already open

### ISSUE THREAD

**Issue by JoeJJJoe** [RequestPolicyContinued/requestpolicy#648] opened 2015-05-18 14:09 UTC
This seems like a really minor thing, but I find it a bit irritating:

With most extensions (including the old RP), clicking the menu button again while the menu is open closes the menu. With RPContinued this isn't the case, and the menu always stays open unless the user clicks somewhere else.

**Comment by myrdd** [comment] 2015-05-18 23:36
Can someone please confirm this bug? I can't reproduce it

**Comment by JoeJJJoe** [comment] 2015-05-19 09:53
In case this helps: I'm using Windows 7 with Firefox 38.0.1.

**Comment by nodiscc** [comment] 2015-05-19 13:28
@myrdd Indeed this seems to happen only on Windows. Iceweasel 38 on Debian is not affected.

**Comment by myrdd** [comment] 2015-05-19 15:30
ok, thanks for the info.

**Comment by l-i-r-n-f-a** [comment] 2015-05-23 02:01
I can confirm the bug for 1.0beta9.3 and Win XP and second JoeJJJoe's request. The closing of the menu after clicking the toolbar button is standard behaviour in RP 0.5 and RPC 0.5beta. Thanks

**Closed** 2016-01-16 21:54 UTC
Labels: bug, user interface
