### ISSUE TITLE
Default to whitelisting mode or ask user during install

### ISSUE THREAD

**Issue by Korodny** [RequestPolicyContinued/requestpolicy#644] opened 2015-05-16 14:10 UTC
Old RequestPolicy would block *all* 3rd party requests, only the ones explicitly allowed by the user were getting through. RPC does offer that option, but it has to be activated manually - and I initially missed this config option, because I didn't expect to find it under "predefined rules" (or whatever it's called in English).

I think "opt-in" should be the default, not "opt-out". Users switching from old RP might not even realise immediately that this has changed, since they'll be used to having the most frequented sites work properly, so they won't see a difference.

If opt-in is not considered user friendly enough, ask the user during installation. Or at least inform him, especially if an old RP installation is detected.

**Comment by nodiscc** [comment] 2015-05-18 16:42
Hi @Korodny this is part of https://github.com/RequestPolicyContinued/requestpolicy/issues/545. The initial setup procedure would let the user choose between default allow/deny and let them enable/disable subscriptions.

I also think the mode checked by default should be _block_, but switching should be really straightforward from the initial setup page.

Closing this as a duplicate of #545, please follow this issue instead.

**Closed by nodiscc** 2015-05-18 16:42 UTC
Labels: duplicate

**Comment by myrdd** [comment] 2015-05-18 23:48
This is in fact a duplicate of #614. When the initial "default policy" will be "deny", then this will be also the case for upgrades from 0.5.x
