### ISSUE TITLE
Requests triggered by the New Tab page aren't blocked

### ISSUE THREAD

**Issue by flussence** [RequestPolicyContinued/requestpolicy#666] opened 2015-06-06 01:46 UTC
Steps to reproduce:

* Completely wipe the browser cache, including the new tab page thumbnails
* Open the browser console window (Ctrl+Shift+J) with full logging enabled to watch what's happening
* Open the New Tab page, let it sit for a while, and note that the thumbnails slowly reappear one by one with all subresources loaded and visible.

For me, this is a huge abuse of privacy and trust on Mozilla's part. I was under the impression those thumbnails got updated by having the page open, not by broadcasting to the sites that I have that page open and burning gigantic amounts of my limited net and CPU resources to do so.

I'll be avoiding that whole anti-feature from now on... is there anything RP can do about it?

**Comment by acrobat1** [comment] 2015-06-06 13:40
That "feature" tracks browsing history in some way, to get rid of it you may want to set **browser.newtabpage.enhanced** to false and **browser.newtabpage.directory.ping** with **browser.newtabpage.directory.source** to a blank.

See: http://forums.mozillazine.org/viewtopic.php?f=7&t=2888321

Maybe such settings should also be added to this ever-growing list of annoyances/unwanted services/privacy intrusions from Mozilla that RP could handle?

**Comment by NinjaSentry** [comment] 2015-06-07 06:46
Would be great if Request Policy had an option to manage background requests. 

uMatrix allows you to set a rule to block hidden callbacks ( moz etc )
( origin | destination | resource | permission )
```
behind-the-scene tiles.services.mozilla.com * block
```
```
behind-the-scene tiles.services.mozilla.com image block
```

With NoScript you could enable **ABE** and add a rule 
```
Site tiles.services.mozilla.com 
Deny
```

> Maybe such settings should also be added to this ever-growing list of annoyances/unwanted services/privacy intrusions from Mozilla that RP could handle?

Adding an interface to access more of the privacy / security related user.js preferences would be nice too.
https://github.com/pyllyukko/user.js
https://github.com/CrisBRM/user.js/blob/master/user.js

**Comment by myrdd** [comment] 2015-06-08 20:54
Hi! First of all, it should be able for RequestPolicy to block *most* requests; sadly there are exceptions (#586, #573). However, in this case, I suppose, it's a usual request like most others.

I haven't seen the requests you've talked about so far @flussence; did you check RP's request log? If you could provide instructions for reproducing in a *fresh profile*, that would help fixing this issue!

The requests in question might be allowed because of some hardcoded *allow rules*, see [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta9.3/src/content/lib/request-processor.compat.js#L194) and [there](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta9.3/src/content/lib/request.jsm#L133) for example. If this is the case, they might not be displayed in RP's request log.

---

> Maybe such settings should also be added to this ever-growing list of annoyances/unwanted services/privacy intrusions from Mozilla that RP could handle?

Thanks for your information @acrobat1. I think that RP should allow the user to controly *any* internet requests. So if necessary, yes, RP should handle prefs that affect internet requests – such as it does already for DNS prefetching for example.

> Adding an interface to access more of the privacy / security related user.js preferences would be nice too.
> https://github.com/pyllyukko/user.js
> https://github.com/CrisBRM/user.js

@nodiscc recently proposed [1] to add that list to the prism-break website [2]. The option I would mostly prefer is to have an extra addon that helps you manage those preferences that impact privacy/security. I think RP's focus should stay on the *requests*.
[1] https://github.com/nylira/prism-break/issues/1254
[2] https://prism-break.org/en/

**Comment by myrdd** [comment] 2015-06-08 21:06
I just did a search for an addon for managing privacy/security preferences, and I've found some addons (and an article) that might be interesting:

 * [PrivacyFox](https://addons.mozilla.org/en-US/firefox/addon/privacyfox/), has been uploaded to AMO just two weeks ago. (license: GPL 3.0)
 * [Tinfoil](https://addons.mozilla.org/en-US/firefox/addon/tinfoil/) (license: MPL 2.0)
 * [overview of security/privacy prefs](http://www.ghacks.net/overview-firefox-aboutconfig-security-privacy-preferences/), article on ghacks.net

Maybe also interesting:

* [Preferences Monitor](https://addons.mozilla.org/en-us/firefox/addon/preferences-monitor/) (MPL 1.1)
* [PrefBar](https://addons.mozilla.org/en-us/firefox/addon/prefbar/)

BTW we could move the discussion about such an addon to another issue – this is quite off-topic here.

**Comment by flussence** [comment] 2015-06-08 21:37
@myrdd - I'll try to reproduce on a fresh profile, but it'd have to wait until the weekend; I'm without access to my desktop until then (if anyone else wants to jump in and do it before then, you're welcome to). Apologies for not doing that to begin with, I only caught this happening while I was in the middle of trying to debug some other problem entirely and so wasn't paying full attention.

The links have been quite informative, thanks all for those.

**Comment by myrdd** [comment] 2016-08-14 17:29
@flussence I still cannot reproduce the issue. Are you still seeing this problem? What are the exact steps to reproduce the issue?

**Comment by flussence** [comment] 2016-08-15 16:20
Sorry, I forgot all about this and I ended up ditching Firefox permanently not long after. If nobody else cares to complain it's probably not worth following up on.

**Comment by myrdd** [comment] 2016-08-15 21:30
Alright, I'll close this issue then.

**Closed by myrdd** 2016-08-15 21:30 UTC
Labels: discussion, unconfirmed
