### ISSUE TITLE
toolbar icon position reset at every startup

### ISSUE THREAD

**Issue by benoit-pierre** [RequestPolicyContinued/requestpolicy#585] opened 2015-01-26 14:50 UTC
Every time I restart Firefox, the RequestPolicy toolbar icon get reset to the right of the navigation bar.

After investigating the issue I noticed 2 things:

1. with Australis, the addon bar does not exists anymore, so I'm using Classic Theme Restorer to get back the old interface; but the addon bar added by the extension is named `"ctraddon_addon-bar"` (not `"addon-bar"`). How about adding it to the list of valid toolbars?
	```diff
	diff --git i/src/content/ui/overlay.js w/src/content/ui/overlay.js
	index 6117f4c..fbdbebb 100644
	--- i/src/content/ui/overlay.js
	+++ w/src/content/ui/overlay.js
	@@ -172,6 +172,7 @@ requestpolicy.overlay = {
	     }

	     var toolbars = [
	+      "ctraddon_addon-bar",
	       "addon-bar",
	       "nav-bar",
	       "toolbar-menubar",
	```

2. after adding some traces, I found out that during initialization, a call to  `this._loadConfigAndRules();` errors out:
	```diff
	diff --git i/src/components/requestpolicyService.js w/src/components/requestpolicyService.js
	index 68fd94b..305d65a 100644
	--- i/src/components/requestpolicyService.js
	+++ w/src/components/requestpolicyService.js
	@@ -1031,7 +1031,11 @@ RequestPolicyService.prototype = {
		 // accessible. If we tried to load preferences before this, we would get
		 // default preferences rather than user preferences.
		 this._syncFromPrefs();
	+	try {
		 this._loadConfigAndRules();
	+	} catch (e) {
	+	dump('profile-after-change: _loadConfigAndRules: ' + e + '\n');
	+	}
		 this._initVersionInfo();
		 // Detect other installed extensions and the current application and do
		 // what is needed to allow their requests.
	```
	The exception is:
	```
	profile-after-change: _loadConfigAndRules: TypeError: curLevel.getLowerLevel is not a function
	```
	Witch result in `this._initVersionInfo` never being called (among others). After looking into it, the problem is due to one of the subscriptions (from `official/deny_trackers.json`): `*.ad.watch.impress.co.jp`. The problem is `watch` is a standard object property name:
	```javascript
	js> ({})['watch']
	function watch() {[native code]}
	js> typeof(Object.create(null)['watch'])
	"undefined"
	js>
	```
	The following patch takes care of the problem:
	```diff
	diff --git i/src/content/lib/ruleset.jsm w/src/content/lib/ruleset.jsm
	index 971ed5e..f213461 100644
	--- i/src/content/lib/ruleset.jsm
	+++ w/src/content/lib/ruleset.jsm
	@@ -643,7 +643,7 @@ function DomainEntry(name, fullName, higher) {
	   this._name = name;
	   this.fullName = fullName;
	   this._higher = higher;
	-  this._lower = {};
	+  this._lower = Object.create(null);
	   this.rules = new Rules();
	 }
	```

**Comment by myrdd** [comment] 2015-01-26 15:01
Wow, that's a great explanation @benoit-pierre 

1. @LtPinback already reported that problem in #580. I've closed that issue because the problem is solved on the [`dev-restartless-and-e10s`](https://github.com/RequestPolicyContinued/requestpolicy/tree/dev-restartless-and-e10s) branch which will be merged for the next beta release. I could create a hotfix if you and/or @LtPinback wish and if it's not too difficult.

2. This bug has already been fixed by @codeman38, see #582. Version `1.0.beta8.2` should have fixed that problem, can you please check if it's fixed for you, too?

**Comment by benoit-pierre** [comment] 2015-01-26 15:11
Oups, sorry for the noise, I did not think to check in *closed* issues too...

1. OK, I can wait for the next beta release.
2.  I just updated to the latest git verson, and I can confirm it works!

**Comment by myrdd** [comment] 2015-01-26 15:26
Great! :) Thank you for your effort!

**Closed by myrdd** 2015-01-26 15:26 UTC
Labels: duplicate
