### ISSUE TITLE
Destination 'null' cannot be allowed on youtube

### ISSUE THREAD

**Issue by 04a391c1b7aa** [RequestPolicyContinued/requestpolicy#685] opened 2015-07-14 13:02 UTC
I don't have flash installed and I disable ublock and noscript for testing, but I still cannot not see html5 videos on youtube when having Request Policy enabled.

![Image of Youtube and Request Policy](https://i.imgur.com/wGC82aj.png)

When i choose to allow request to null then nothing changes and null is still under the blocked destinations. However, when click on "Allow requests to *.youtube.com" then the html5 video loads (and when I disable Request Policy it also loads).

**Comment by nodiscc** [comment] 2015-07-14 18:42
duplicate of #626.

> You can work around this problem by manually adding a rule from  host `*.youtube.com` to destinations with scheme `mediasource`.

the main tracking issue is #619.

**Closed by nodiscc** 2015-07-14 18:42 UTC
