### ISSUE TITLE
Not signed, wont work anymore in 41+ beta/release versions

### ISSUE THREAD

**Issue by iNetRunner** [RequestPolicyContinued/requestpolicy#701] opened 2015-08-13 11:47 UTC
Since RequestPolicyContinued isn't distributed via addons.mozilla.org, this plugin is not signed. And now that beta release channel has moved to version 41, RequestPolicyContinued stopped working because it isn't signed by Mozilla.

Should RequestPolicy Continued be added as a new add-on to addons.mozilla.org? Or is there a plan to update RequestPolicy plug-in with this code when 1.0 final is released?

**Comment by ivan-kolmychek** [comment] 2015-08-13 12:40
See #600 for this.

**Comment by Diapolo** [comment] 2015-08-14 06:31
That's nice, but it seems there is no 1.0.beta11 or a signed beta10 available for download, but Mozilla released 41.0b1 into the wild, which disables the unsigned beta10 :-/.

**Comment by ivan-kolmychek** [comment] 2015-08-14 08:12
Let's hope that @myrdd will get the signature before 41 will be released on __stable__ channel. ;)

**Comment by sugatov** [comment] 2015-08-16 10:29
This may help:
go to `about:config` and set a parameter named as `xpinstall.signatures.required` to `false`. This should disable signature check.

**Comment by genodeftest** [comment] 2015-08-16 15:37
@sugatov This about:config option won't be present in Firefox stable/final.

**Comment by sugatov** [comment] 2015-08-16 15:43
@genodeftest As far as I know this should be there up to Firefox 41 in beta/release and 42+ in aurora/central.

**Comment by myrdd** [comment] 2015-08-16 18:22
Sorry for the late reply. It's true, a signed release already makes sense for Firefox-Beta users, so I'll offer it: Download and install the signed version from [here](http://requestpolicy.256k.de/requestpolicy-1.0.beta10.0.3signed.xpi). **Please test it.** That release should be functionally equal to the "beta10". You need to install it manually, because many unit tests are currently broken (#641). Please report any problem specific to that signed version.

**Comment by Diapolo** [comment] 2015-08-17 06:07
@myrdd I'd love to test the extension, but I don't trust plain http-URLs anymore. COuld you upload that build to the normal download page of your great addon?

**Comment by ivan-kolmychek** [comment] 2015-08-17 07:43
@Diapolo it's signed anyway - noone can tamper with extension without damaging its signature, even on http. ;)

**Comment by myrdd** [comment] 2015-08-18 00:00
Yes you are right, Ivan, if a mitm sends you a different, unsigned package, you should see a warning in ff that this extension is unsigned. If you ignore that message, the signature didn't help.

Anyway, the same file over https:  https://sslsites.de/requestpolicy.256k.de/requestpolicy-1.0.beta10.0.3signed.xpi

**Comment by Diapolo** [comment] 2015-08-18 13:59
Thanks for supporting download via https :). I can confirm FF 41.0b1 accepts and installst the signed addon file. RPC works like it should, great.

**Comment by myrdd** [comment] 2015-09-09 11:29
Alright, no complaint in three weeks, I'll officially release the signed version today.

**Comment by myrdd** [comment] 2015-09-09 13:20
manual and automatic update to `1.0.beta10.1-signed` should work now.

- [Release tag](https://github.com/RequestPolicyContinued/requestpolicy/releases/tag/v1.0.beta10.1-signed)
- [Release commit](https://github.com/RequestPolicyContinued/requestpolicy/commit/0eb896e6669a5144adc84d0392f6ab515d531f06)
- [Website commit](https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/commit/0c9d25907c406b422812026ab9a1d04edf7d83ff)

**Closed by myrdd** 2015-09-09 13:20 UTC

**Comment by ivan-kolmychek** [comment] 2015-09-09 13:23
@myrdd confirming automatical update, Firefox `40.0.3`. Thanks.
