### ISSUE TITLE
RequestPolicyContinued + Enpass Browser Extension Problem

### ISSUE THREAD

**Issue by ralle12345** [RequestPolicyContinued/requestpolicy#732] opened 2015-11-10 12:58 UTC
Hi,
RequestPolicyContinued 1.0beta10.2 and Enpass 5.0.4 (http://enpass.io) don't play nice when enabled in the same profile. Enpass does not seem to do anything anymore when both are extensions are there.  

If however RequestPolicy is disabled when the browser starts and enabled later, everything works fine.

I looked in the "Browser console" for errors but there are none when I click on the extension's tool bar icon. There aren't any errors in the terminal window when firefox is started from the console either.

If there is any other way I can debug this problem I'll gladly try to find out more.

**Comment by myrdd** [comment] 2015-11-10 14:02
Hi, my first guess is that Enpass is wrapping a Firefox function or something like that.

Looks like Enpass is not free software, so I'm not sure how much I can do. Still, you could enable RP logging, see [here](https://github.com/RequestPolicyContinued/requestpolicy/wiki/Setting-up-a-development-environment#summary).

**Comment by ralle12345** [comment] 2015-11-11 06:49
I will try that and see what it shows.

In the meantime I found out that I can get both extensions running together by disabling both and the first enabling enpass and then RP.

**Comment by myrdd** [comment] 2015-11-12 18:14
Another idea is to check the request log:

1. Disable both extensions
2. Enable RP, open the request log
3. Enable Enpass

Then see if the request log shows a blocked request which might come from Enpass.

**Comment by ralle12345** [comment] 2015-11-13 11:46
I didn't have time to followup to this. I'll try to do some research on the weekend.

**Comment by ralle12345** [comment] 2015-12-02 09:30
I also contacted Enpass because of this conflict. The solution provided by Enpass is to create two rules:

1. Allow **from** Scheme enpassextension://
2. Allow **to** host localhost

This solves the problem for me.

**Comment by myrdd** [comment] 2015-12-02 20:51
Thanks for your investigation, I will add a compatibility rule to RequestPolicy.

**Comment by myrdd** [comment] 2015-12-06 19:53
The issue is fixed in v1.0.beta11pre2. @ralle12345 please confirm that Enpass works without a user-defined rule.

**Closed by myrdd** 2015-12-06 19:53 UTC
Labels: easy, extension conflict, unconfirmed

**Comment by ralle12345** [comment] 2015-12-08 12:00
I removed the old version of the extension, installed the new one, removed the user rules (forgot to do that before installing the new version) and restarted the browser. Now it seems those two extensions play nice when installed together :)

**Comment by myrdd** [comment] 2015-12-08 18:07
Great! Thanks for checking.
