### ISSUE TITLE
doesn't work anymore....

### ISSUE THREAD

**Issue by GianniGi** [RequestPolicyContinued/requestpolicy#886] opened 2018-01-11 22:31 UTC
Read first: https://requestpolicycontinued.github.io/Contributing

__Browser and Add-ons:__

- Browser: 57.0.4 (64-bit)
- OS ubuntu 17.10
- RequestPolicy version: what??

RequestPolicy settings:
- Default policy: "allow" / "deny"
default settings, I've tried to reset them, and to uninstall and reinstall the addon

__Steps to reproduce:__
I've tried to install and uninstall the addon

__What happens?__

nothing shows 

__What should happen?__

In old versions of firefox everything worked, probably before 57

**Comment by jrrdev** [comment] 2018-01-12 00:39
For the moment, Request Policy isn't compatible with Firefox >= 57 because the old XUL/XPCOM API can't be used anymore. See #704 for current status of the ongoing work to port to the new WebExtension API.
Until the port is finished, if you want to use a browser with Request Policy enabled, I recommend to use the ESR version of Firefox. The package name is `firefox-esr` on Ubuntu

**Comment by myrdd** [comment] 2018-01-16 06:37
duplicate of #704

**Closed by myrdd** 2018-01-16 06:37 UTC
