### ISSUE TITLE
Config option to switch redirect handling on/off

### ISSUE THREAD

**Issue by Korodny** [RequestPolicyContinued/requestpolicy#654] opened 2015-05-20 00:23 UTC
I realise there are several issues open regarding how redirects are handled and how the user should be given more control over them, but it doesn't seem like there's one covering a global config option for redirects.

My 'problem' is: I simply don't mind redirects. If the URL to one of the objects embedded in the current page redirects to some other server, RPC's existing rules should be applied to determine if the object is loaded or not. If I click on an URL and it redirects somewhere else - so be it. It's not like I'm constantly checking URLs I click on, so an URL redirecting somewhere else doesn't really bother me all that much.

A configuration option in the settings dialog would be nice.

**Comment by myrdd** [comment] 2015-05-20 18:52
duplicate of #53.

**Closed by myrdd** 2015-05-20 18:52 UTC
Labels: duplicate
