### ISSUE TITLE
Blocklist is broken in b11pre4

### ISSUE THREAD

**Issue by sataevr** [RequestPolicyContinued/requestpolicy#746] opened 2016-01-02 21:38 UTC
I am use "block requests by default" and something bad happens after update to beta11pre4.

Allow *.twimg.com to *.twimg.com deny_trackers;
allow *.twitter.com to *.twimg.com deny_trackers;
allow *.twitter.com to *.twitter.com deny_trackers;
block to *.twimg.com deny_trackers;
block to *.twitter.com deny_trackers;
and allow *.twitter.com to *.twimg.com allow_sameorg;
at the same time.

Now Twitter can't access to twimg without "stop blocking request to twimg.com".

**Comment by myrdd** [comment] 2016-01-02 23:08
beta11pre4 introduced this change:

* Subscription rules now apply regardless of the current default policy (#529)

Therefore the `deny_trackers` subscription list suddenly got activated if you're in "default deny" mode. Said list contains "conflicting rules" for a request from `*.twitter.com` to `*.twimg.com`, that is, there are both "allow" and "deny" rules. In such a case RP (currently) falls back to the default policy. I consider this to be a bug, which is tracked in #491.

I know the problem you've been describing, specifically regarding twitter, has been introduced in beta11pre4, but still the change made in #529 is deliberate – I'm closing this issue in favor of #491.

**Closed by myrdd** 2016-01-02 23:08 UTC

**Comment by timkuijsten** [comment] 2016-01-14 14:32
+1

**Comment by myrdd** [comment] 2016-01-15 09:58
If #491 is fixed, this will be fixed as well, because `*.twitter.com -> *.twimg.com` will take precedence over `* -> *.twimg.com`.

![twimg.com rules](https://cloud.githubusercontent.com/assets/4286829/12350358/d31cdd28-bb76-11e5-9160-37121fba1edd.png)

**Comment by myrdd** [comment] 2016-02-02 14:16
The issue is fixed in the latest nightly :)

**Comment by timkuijsten** [comment] 2016-02-02 14:17
yup, I can confirm I can connect to twitter again :) tnx!
