### ISSUE TITLE
Conflict(?) with Tab Mix Plus addon

### ISSUE THREAD

**Issue by Dezaimasu** [RequestPolicyContinued/requestpolicy#708] opened 2015-09-12 10:11 UTC
There's some conflict between RPC and Tab Mix Plus addon.
https://addons.mozilla.org/ru/firefox/addon/tab-mix-plus/
This happens only when RPC is enabled on startup. If it's disabled when I start Firefox, and enabled later via add-ons panel, everything works fine.

Tab Mix Plus has an option to open all new tabs next to the current one. But this option doesn't works with RPC, and all new tabs (links from the page, bookmarks, history, etc.) are opened as a last one. Only Ctrl+T opens new tab next to the current one.

I've noticed this just today, using TMP 0.4.1.9 and RPC v1.0.beta10.1-signed. Firefox 40.0.3, Win 7 x64.
Tried to recreate this bug with new profile and only TMP and RPC installed, everything still worked exactly as I described.

**Comment by ShyWest** [comment] 2015-09-12 14:42
I have the same issue, except it's the other way around. I had Tab Mix Plus configured to open all new tabs as the last one, but since RPC last release it always opens them next to the current tab ignoring the configuration. The only way to fix the issue is start Firefox with RPC disabled. Enabling RPC during runtime doesn't produce the issue. Likewise, disabling RPC during runtime doesn't fix the issue.

I'm running TMP 0.4.1.9, RPC v1.0.beta10.1-signed, Iceweasel 40.0.3 and Debian Stable amd64.

**Comment by powerman** [comment] 2015-09-13 02:46
I've same issue. Downgrading to v1.0.beta10 helps.

**Comment by myrdd** [comment] 2015-09-13 18:26
Thanks for the report. It's about the `gBrowser.addTab` function. RequestPolicy wraps it, whereas TabMixPlus *edits* it, so TMP needs the _original_ function. The conflict here is that TMP does not know where the original function is.

I've sent an email to TMP's support address. I've written a simple [proposal](https://gist.github.com/myrdd/0378963d425c220035e3) to fix the bug also for other add-ons that want to wrap any browser-internal function.

Until the bug is fixed you need to use beta10.

**Comment by myrdd** [comment] 2015-11-06 13:18
The issue has been fixed by the Tab Mix Plus developer.
The fix is released in 0.4.2.0pre.151021a1.
See https://bitbucket.org/onemen/tabmixplus/commits/53d7ea1ec0c6

**Closed by myrdd** 2015-11-06 13:18 UTC
Labels: extension conflict
