### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by doublezeta** [RequestPolicyContinued/requestpolicy#653] opened 2015-05-19 18:07 UTC
I hide my toolbar, including the "File Edit View" menu. The old RequestPolicy had a context menu option to Allow or Deny third-party referrers. Please add this to the add-on, so users don't need a toolbar icon to change their settings.

**Comment by nodiscc** [comment] 2015-05-19 22:20
Hi @doublezeta this is a duplicate of https://github.com/RequestPolicyContinued/requestpolicy/issues/353. Please follow this issue instead.

**Closed by nodiscc** 2015-05-19 22:20 UTC
