### ISSUE TITLE
The add-on leaks memory

### ISSUE THREAD

**Issue by sander85** [RequestPolicyContinued/requestpolicy#672] opened 2015-06-20 15:22 UTC
It's OK at first but with few days running it's memory usage grows and grows until Firefox becomes slow to use and has to be restarted. Doesn't happen if this add-on is disabled.

Output from about:memory

```
├─────67.59 MB (05.67%) -- add-ons
│     ├──58.08 MB (04.87%) -- requestpolicy@requestpolicy.com
│     │  ├──57.13 MB (04.79%) -- js-non-window/zones/zone(0x7f8e2d42e800)
│     │  │  ├──26.14 MB (02.19%) -- compartment([System Principal], chrome://requestpolicy/content/lib/request-result.jsm)
│     │  │  │  ├──23.63 MB (01.98%) -- classes
│     │  │  │  │  ├──17.12 MB (01.44%) -- class(Array)
│     │  │  │  │  │  ├──17.12 MB (01.44%) -- objects
│     │  │  │  │  │  │  ├──17.12 MB (01.44%) ── gc-heap
│     │  │  │  │  │  │  └───0.00 MB (00.00%) ++ malloc-heap
│     │  │  │  │  │  └───0.00 MB (00.00%) ++ shapes
│     │  │  │  │  └───6.51 MB (00.55%) ++ (3 tiny)
│     │  │  │  └───2.51 MB (00.21%) ++ (2 tiny)
│     │  │  ├──20.47 MB (01.72%) ++ compartment([System Principal], chrome://requestpolicy/content/lib/request-set.jsm)
│     │  │  └──10.53 MB (00.88%) ++ (31 tiny)
│     │  └───0.95 MB (00.08%) ++ window-objects/top(none)/detached/window(about:requestpolicy?yourpolicy)
```
Not too hard to reproduce, just don't restart your browser for a few days.

Firefox: 39
RequestPolicy: 1.0.beta9.3

**Comment by myrdd** [comment] 2015-06-20 20:44
duplicate of #588

**Closed by myrdd** 2015-06-20 20:44 UTC
