### ISSUE TITLE
speeddial blank thumbnails

### ISSUE THREAD

**Issue by klore** [RequestPolicyContinued/requestpolicy#657] opened 2015-05-21 17:43 UTC
when using sepeedial with groups tabs (don't know without groups tabs) thumbnails turn blank after restart

**Comment by nodiscc** [comment] 2015-05-21 20:45
Hi @klore can you link to the speedial addon you're referring to? Do any requests show up in the RPC menu when you are on the speeddial page?

I'm thinking RPC just does it's job by blocking requests from this page, you should be able to allow them manually (if not, it's a bug).

**Comment by klore** [comment] 2015-05-22 04:29
Hello, this is the addon,
https://addons.mozilla.org/ES/firefox/addon/speed-dial/?src=search

There is no options (origin) to allow or block in speeddial page/tabs, maybe can add a rule in manage policy but don't know 

speeddial link,

chrome://speeddial/content/speeddial.xul

thank you

**Comment by myrdd** [comment] 2015-05-22 04:47
@klore try adding an allow rule from `resource://gre-resources` to `file:*` (on `about:requestpolicy?yourpolicy`).

If this solves your problem, please tell me, don't close this issue. I'll  create a compatibility rule for RequestPolicy.

**Comment by klore** [comment] 2015-05-25 17:28
Hello, I created a rule chrome://speeddial/content/speeddial.xul localhost? 80? same blank thumbs
I realized in about:requestpolicy?defaultpolicy if i "allow requests by default" thumbnails back, but "block requests by default" are blank

**Comment by myrdd** [comment] 2015-05-26 12:27
@klore see this screenshot:

![rule](https://cloud.githubusercontent.com/assets/4286829/7812502/1edde468-03b3-11e5-95b4-05218788324e.jpg)

the result should be as follows:

![rule-in-table](https://cloud.githubusercontent.com/assets/4286829/7812510/3d02e574-03b3-11e5-9da4-33cc11ddeca3.jpg)

**Comment by klore** [comment] 2015-05-26 17:49
It doesn't work, still blank thumbs with "block requests by default" marked
, working with "allow requests by default" marked

**Comment by myrdd** [comment] 2015-05-26 20:22
@klore if this is the case, could you please open the Request Log by yourself and see what requests are being blocked?

**Comment by klore** [comment] 2015-05-27 03:48
Hello, the request log is empty in chrome://speeddial/content/speeddial.xul
Also I created a new clean firefox profile, without touching the about:config and only with speedial & requestpolicy, it doesn't work, same as before

**Comment by Radagast** [comment] 2015-05-27 05:33
Unable to recreate here with fx 38.0.1/speeddial 9.6.17

Speeddial - Group Tabs
RPC - block all/no subscriptions

Dials load and persist after restart.

**Comment by myrdd** [comment] 2015-05-27 07:07
@klore you have to open the request log *before* opening the new tab that contains speeddial. My suggestion: 
1. add the rule that I've mentioned above
2. open the request log
3. open a tab with speeddial
4. add a new "tile" to speeddial and/or reload a speeddial "tile" that previously has been blocked
5. check the request log for blocked requests

**Comment by klore** [comment] 2015-05-27 16:44
Hi, with 1 2 3 was enought, it's really working, not only with group tabs also with stand alone tab
I am very grateful, thank you very much :)

**Comment by myrdd** [comment] 2015-05-27 22:15
Great! So I'll add a compatibility rule to the next release:

Allow requests from `resource://gre-resources` to `file:*` when *Speed Dial* is installed.

*Speed Dial*'s ID is `{64161300-e22b-11db-8314-0800200c9a66}`

**Comment by myrdd** [comment] 2016-08-14 08:05
I forgot to add this comptibility rule, but it looks like the rule isn't necessary anymore. At least I can't reproduce the issue. Closing.

**Closed by myrdd** 2016-08-14 08:05 UTC
Labels: extension conflict
