### ISSUE TITLE
[e10s] Unable to allow Website's Redirect

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#620] opened 2015-04-23 11:47 UTC
Nightly: 40.0a1 (2015-04-22)
RP: https://github.com/RequestPolicyContinued/requestpolicy/commit/581e2b8547917df903a8d4664728f1c469a5109e
Test Site: http://konvertor.forumactif.com/

Issue: Can not click "Allow" on redirect pop-up in e10s windows. Work fine with non-e10s.

Expected result: Able to click "Allow" and page re-direct expected URL.

Reproduce:
- Go to http://konvertor.forumactif.com/
- RP will pop-up under navigation bar with option: "Allow" "Deny" "add rule", Deny and Add rule function as normal.
- Click "Allow" nothing happen.

**Comment by dawidi** [comment] 2015-04-30 21:52
Not sure if this helps (or is even related), but I'm experiencing the same problem - the "Allow" button on the redirection prompt bar not responding - on the current Pale Moon 25.3.2 (x86) with RPC 1.0.beta9.1. It worked fine until yesterday, not sure which update caused it to stop working.

If I add a (permanent or temporary) rule to RPC, the redirect works, but of course without any prompt.

**Comment by beerisgood** [comment] 2015-05-01 10:41
I have the same problem (using Pale Moon 25.3.2 x64) with RPC 1.0 beta9.1

I can't click on allow, but on deny and add rule which works, but if i click on add rule and allow it, then the urlbar is empty but i get  no reload/ forward.

**Comment by myrdd** [comment] 2015-05-01 11:19
I can reproduce this problem. It works with e10s disabled though.
The Browser Console shows `TypeError: browser.documentURI is null`.

> if i click on add rule and allow it, then the urlbar is empty but i get no reload/ forward.

Oh, true! That's another bug – the page should reload, but it doesn't (on e10s).
The Browser Console shows `TypeError: content is null`.
Yes, the urlbar is empty if the link is opened in a new window. If it's opened in a new tab, the urlbar shows the correct url.

**Comment by dawidi** [comment] 2015-06-10 21:59
The problem still persists with the current (25.4.1) Pale Moon, while it works fine on a "regular" current firefox (presumably without e10s). Is there anything I can do to help with debugging this? (I'm not an addon developer.)

**Comment by myrdd** [comment] 2015-06-11 06:05
Good to know the problem is also present on palemoon. Yes, you could help by opening the Browser Console, if PM has such a feature, to watch what's happening when you reproduce the bug.

**Comment by dawidi** [comment] 2015-06-11 08:43
Ah... I didn't know the "Browser Console" and the "Web Console" log different things even though they look identical.

As an example, clicking on a link in a twitter message (those are always "shortened"/redirected via t.co, and I only want to allow them with the one-off "Allow" button, not add a permanent rule), I get this:

    Component returned failure code: 0x805e0006 [nsIDOMLocation.replace] @ http://t.co/e6vEq1mqkx:1

followed by a successful GET for http://t.co/favicon.ico
The Redirection notifier bar appears, and when I click "Allow":

    TypeError: browser.documentURI is undefined @ chrome://requestpolicy/content/ui/overlay.js:543

and no redirection occurs.
When I then add a temporary rule allowing everything "from *.t.co to *.(destination domain)", and reload the t.co redirection page, the destination page is loaded normally without further log entries related to RequestPolicy.

**Comment by myrdd** [comment] 2015-06-11 10:31
> The Redirection notifier bar appears, and when I click "Allow":
> 
>     TypeError: browser.documentURI is undefined @ chrome://requestpolicy/content/ui/overlay.js:543
> 
> and no redirection occurs.

Looks very similar to the error message for Fx+e10s. The error message points to [this line of code](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta9.3/src/content/ui/overlay.js#l543).

> I switched to Pale Moon about two months ago, and for the first couple of weeks, the "Allow" button on redirection worked fine.

This could mean that Pale Moon 25.5.0, [released yesterday](https://www.palemoon.org/releasenotes.shtml), has introduced this "bug".

I guess this bug could be solved quite quickly, but I'd like to follow a test-first development style consequently. This issue's milestone is beta11.

**Comment by dawidi** [comment] 2015-06-11 11:18
> This could mean that Pale Moon 25.5.0, released yesterday, has introduced this "bug".
Ah, no. I switched to Pale Moon with version 25.3.1 (on 2015-03-25) - with whatever version of RPC was current at that time - and it worked then. As noted above, I noticed on 2015-04-29 it had stopped working with 25.3.2 (released 2015-04-25, presumably installed the same day) and RPC 1.0.beta9.1.

I just "updated" to RPC 1.0.beta8.2, and the "Allow" button works fine (with PM 25.5.0 still) - so it must be something that was changed in RPC between betas 8 and 9.

**Comment by myrdd** [comment] 2015-06-11 11:34
> I just "updated" to RPC 1.0.beta8.2, and the "Allow" button works fine (with PM 25.5.0 still) - so it must be something that was changed in RPC between betas 8 and 9.

Thanks for that info! Much code has changed from beta8 to beta9, so yes, it's highly probable the changes introduced the bug.

**Comment by beerisgood** [comment] 2015-06-12 14:57
Yes can confirm that. The problem is between RPC beta 8.* and 9.*
(not Pale Moon relevant)

**Comment by zeorin** [comment] 2015-09-23 18:22
Hi, I'm on the latest RPC (v1.0.beta10.1-signed), and I have this issue. Running FF Nightly 44.0a1. In a non-e10s window redirects work just fine.

In e10s windows nothing happens, and the URL bar is blank (if the link was opened from an external program). If I'm following a link from a web page to a page that responds with a location header, nothing at all happens.

Almost as if the browser finds the location header and then tries to go back 1 URL in the history, which for new windows (opening links from external programs) is obviously empty, so the URL bar is blank. When following a link, that would result in nothing happening (forward 1, back 1).

Browser console shows no errors.

**Comment by beerisgood** [comment] 2015-09-26 08:00
Problem still exist with RPC 1.0beta10.1-signed.
Is their any chance to fix it?

Click on allow button make this error:
TypeError: browser.documentURI is undefined
Source File: chrome://rpcontinued/content/ui/overlay.js
Line: 543

Deny button works without any error.

And temporary allow works but remove the url in urlbar and doesn't redirect to the site- until i put the url again in urlbar.

**Comment by myrdd** [comment] 2015-09-26 14:14
> Is their any chance to fix it?

Still working on Mozmill-Marionette migration, #641. After that I'll look into this issue.

**Comment by myrdd** [comment] 2015-10-21 21:37
The status of this issue changed somehow. The "Allow" button seems to work, but when adding a rule via the redirect notification bar the page does not reload.

There are also more redirection issues, covered by the Marionette unit tests, currently failing on e10s. I suspect that issue #610 needs to be fixed in order to fix _all_ redirection issues.

**Comment by myrdd** [comment] 2015-10-22 01:17
As I said before, clicking the "Allow" button currently works. However, the URL @ldgbc mentioned in the first post, http://konvertor.forumactif.com/, suffers another issue, #722. Please subscribe to that one if you want to stay informed.

**Closed by myrdd** 2015-10-22 01:17 UTC
Labels: bug, e10s

**Comment by myrdd** [comment] 2015-10-30 01:05
This issue, as well as #722, should be fixed in the next release.
