### ISSUE TITLE
Request log can't detect redirections to https on http page properly with newest versions of Noscript.

### ISSUE THREAD

**Issue by ghost** [RequestPolicyContinued/requestpolicy#775] opened 2016-03-29 17:21 UTC
From Noscript 2.9.0.7 and up request log can't detect that ia.media-imdb.com redirects  to https forced by Noscript on imdb.com and show just http links there, when network developer tool and browser console show that connection is secure.  
I  discussed this issue here: 
https://forums.informaction.com/viewtopic.php?f=7&t=21775

**Comment by myrdd** [comment] 2016-03-30 02:38
I can confirm that there are _less_ https requests in RP's request log, at least at the first load of `imdb.com`. The NoScript version which changed the behavior is `Version 2.9.0.7rc2` ([AMO](https://addons.mozilla.org/en-US/firefox/addon/noscript/versions/?page=1#version-2.9.0.7rc2), [source diff](https://github.com/avian2/noscript/commit/97a6019543fb98e59ff9d4900a1b10d27d45b6bf)).

I think the main problem here is that, after `nsIHttpChannel.redirectTo()` ([MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIHttpChannel#redirectTo%28%29); available [since Fx21](https://bugzilla.mozilla.org/show_bug.cgi?id=765934)) has been called, the content-policy is _not_ called again with the new URI.

@gineadai Note that the request log only displays the URLs which have been passed to RP for checking if it may be loaded. URLs which are not blocked can still be redirected at a later time, before the http channel is opened.

So how to resolve this?

I guess what should be implemented is to watch for redirected URLs ([`nsIChannelEventSink`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIChannelEventSink)) and do some magic. For example, the request log could show that the _actual_ destination was distinct from the URL at blocking-time. _But_, in fact redirects also affect the menu, since the menu represents the same URLs as shown in the request log; not sure what to do in the menu.

I guess that `redirectTo()` accepts redirections not only to web locations, but also to local files, such as in the case of the [decentraleyes add-on](https://github.com/Synzvato/decentraleyes), which [uses](https://github.com/Synzvato/decentraleyes/blob/f5f0154cfd40ab34c9cb223766f9ad33c39942fa/lib/interceptor.js#L115) `redirectTo()` as well. In any case, `redirectTo()` needs to be investigated; the discussion on [Bug 765934](https://bugzilla.mozilla.org/show_bug.cgi?id=765934) should be a good point to start.

Suggestions welcome!

**Comment by stepshal** [comment] 2016-06-11 08:47
Similar Issue fixed in here: https://github.com/gorhill/uMatrix/issues/554

**Comment by myrdd** [comment] 2016-06-11 17:38
Thanks for the link. The uMatrix issue has to do with `redirectTo` as well, but it's about adding metadata to the channel. The issue with RP is that RP doesn't implement `nsIChannelEventSink`, hence any calls to `redirectTo` aren't observed.

It looks like being as follows: If `redirectTo` is called, or the server returns a `Location` header, then the `nsIChannelEventSink` implementations will be called. However, if the server returns a `Refresh` header, then `shouldLoad` will be called instead.

So the solution should be as simple as implementing `nsIChannelEventSink`. The observer for `http-on-examine-response` probably can be removed, since it's only used to block `Location` and `Refresh` header redirects.

**Comment by myrdd** [comment] 2016-06-12 16:18
> So the solution should be as simple as implementing `nsIChannelEventSink`.

Indeed, looks like what I've said solves this issue. However, the change introduces a new issue, which leads the browser's back-button to misbehave; needs to be fixed.

**Comment by myrdd** [comment] 2016-06-21 21:00
The issue should be fixed in version [`1.0.beta12.0.1496.rf8c4caa.pre`](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/1.0.beta12.0.1496.rf8c4caa.pre). Could you please verify?

(fixed in commit f8c4caabb7d56725e7d871cbf97f45d1c3bf1354)

**Closed by myrdd** 2016-06-21 21:00 UTC
Labels: discussion

**Comment by stepshal** [comment] 2016-06-22 13:10
@myrdd I don't know, seems to be a problem on Noscript side as well. When i add `ia.media-imdb.com` to list of sites to be forced to use https,  Noscript not showing https addres of `ia.media-imdb.com`,  just http. So, when RequestLog show `http://` on `ia.media-imdb.com` when request from there not allowed is okay. But when i allow requests from there, output become very strange. It shows that stylesheet requests from `imdb` to `ia.media-imdb.com` go through http, and image requests go through both `http` and `https` . And then go request  with stylesheet and images from `http://ia.media-idmb.com` to `https://ia.media-idmb.com`, and at the end two stylesheet requests go to image requests from and to `https://ia.media-idmb.com` both.  Browsers Network tool show the same as before, and i check in Blockable items of Adblock Plus, there is same URLs in http and https both.

**Comment by myrdd** [comment] 2016-06-24 07:11
@stepshal please provide some more information, e.g. a screenshot. When you tell NoScript to force https for the `ia.media-imdb.com` domain, you should now see two requests for each "actual" request in the Request Log.  In other words:

* tell NoScript to force https for the `ia.media-imdb.com` domain
* visit `http://www.imdb.com`
* the request log should show kind of duplicate requests:
  * Request A: `http://www.imdb.com/  -->  http://ia.media-imdb.com/<path>`
  * Request B: `http://ia.media-imdb.com/<path>  -->  https://ia.media-imdb.com/<path>`
* Explanation:
  * Request A is the request the website wants to perform.
  * Request B is the redirection by NoScript. So it's in fact no request, but the "https" destination is what will finally be requested (leaving the browser).
