### ISSUE TITLE
Dealing with redirects?

### ISSUE THREAD

**Issue by Radagast** [RequestPolicyContinued/requestpolicy#756] opened 2016-01-17 23:36 UTC
Just wondering what the best way of dealing with multiple redirects. In the following example, a link from a DDG search is selected

![Imgur](http://i.imgur.com/l0k7CYP.jpg)

There are 4 more redirects than shown before getting to the site.

Using:
* 1.0.beta11pre4.1436.rb482daa (default deny no subscriptions)
* fx 45.0a2 (2016-01-17) (e10s off)

With Allow requests to the same domain (www.example.com -> static.example.com). selected I only get 4 redirects...

**Comment by myrdd** [comment] 2016-01-18 09:17
I've never seen that many redirects. It looks like a loop; maybe another add-on or a Firefox setting causes this problem? – please [test in a new, blank profile](https://requestpolicycontinued.github.io/Contributing). Also, could you please give me a specific URL which shows this problem reproducibly?

**Comment by Radagast** [comment] 2016-01-19 00:10
Clean profile (43.0.4) jus RPC configured with default deny, 'only' 4 redirects. 

![Imgur](http://i.imgur.com/2Ewe7us.jpg)

**Comment by myrdd** [comment] 2016-01-19 13:47
> could you please give me a specific URL which shows this problem reproducibly

?

**Comment by Radagast** [comment] 2016-01-19 22:13
As mentioned, it was a link from a DDG search. I believe the url was http://answers.microsoft.com/en-us/windows/forum/windows_8-gaming/all-my-games-has-a-problem-with-my-direct3d/f1101d7e-6837-4daf-8591-e8047b2196d1

**Comment by myrdd** [comment] 2016-01-20 08:59
Okay, you're right. In a fresh profile there are four redirections. I tested it for a DDG search. These are the URLs the page load will go through.

* __`http://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/direct3ddirectx-issues/fd7ca462-f53a-4a45-9cd1-818dbe2a02a3`__
* `https://answers.microsoft.com/en-us/site/startsignin?pageUrl=http%3A%2F%2Fanswers.microsoft.com%3A80%2Fen-us%2Fwindows%2Fforum%2Fwindows_other-gaming%2Fdirect3ddirectx-issues%2Ffd7ca462-f53a-4a45-9cd1-818dbe2a02a3%3Fauth%3D1&silent=True`
* `https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&checkda=1&ct=1453278913&rver=6.5.6509.0&wp=LBI&wreply=https:%2F%2Fanswers.microsoft.com%2Fen-us%2Fsite%2Fcompletesignin%3Fsilent%3DTrue%26returnUrl%3Dhttp%253A%252F%252Fanswers.microsoft.com%253A80%252Fen-us%252Fwindows%252Fforum%252Fwindows_other-gaming%252Fdirect3ddirectx-issues%252Ffd7ca462-f53a-4a45-9cd1-818dbe2a02a3%253Fauth%253D1&id=273572`
* `https://answers.microsoft.com/en-us/site/completesignin?silent=True&returnUrl=http%3A%2F%2Fanswers.microsoft.com%3A80%2Fen-us%2Fwindows%2Fforum%2Fwindows_other-gaming%2Fdirect3ddirectx-issues%2Ffd7ca462-f53a-4a45-9cd1-818dbe2a02a3%3Fauth%3D1`
* __`http://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/direct3ddirectx-issues/fd7ca462-f53a-4a45-9cd1-818dbe2a02a3?auth=1`__

I think this is a candidate for the `allow_sameorg` subscription.

I could imagine that you're getting so many redirections in your other profile – referring to your first post – because you're blocking cookies or something similar, which is needed in this case. I guess this is a `wontfix`; the solution is to add allow-rules between `*.live.com` and `*.microsoft.com`.

**Closed by myrdd** 2016-01-20 08:59 UTC
Labels: usability

**Comment by myrdd** [comment] 2016-01-20 09:08
Okay, in fact it's `invalid`, because there's nothing to fix here. If you've got a suggestion, go ahead.

Regarding the subscription rule: https://github.com/RequestPolicyContinued/subscriptions/issues/39
