### ISSUE TITLE
Alphabetical sorting of rules in Manage Policies

### ISSUE THREAD

**Issue by berdinso** [RequestPolicyContinued/requestpolicy#709] opened 2015-09-13 21:17 UTC
I'd like an option to alphabetically sort the rules in Manage Policies by origin and destination. Right now they seem like are ordered by date added, so it's difficult to see groupings without resorting to the search filter.

**Comment by myrdd** [comment] 2015-09-13 22:24
Duplicate of #343 :)

**Closed by myrdd** 2015-09-13 22:24 UTC
