### ISSUE TITLE
Cannot use new "Sign in to Sync" in Firefox 29.0 beta

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#426] opened 2014-07-07 00:37 UTC
<a href="https://github.com/bz922x"><img src="https://avatars.githubusercontent.com/u/3180632?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bz922x](https://github.com/bz922x)**
_Friday Mar 21, 2014 at 14:08 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/426_

----

When RequestPolicy 1.0 is turned on with default blocking, the new "Sign in to Sync" page will display, but the pressing the "Get Started" button displays a blank page.

It is not enough to click the RequestPolicy "Disable Blocking" after the "Sign in to Sync" page is displayed, "Disable Blocking" must be clicked before selecting "Sign in to Sync" from the new Firefox main menu.

**Comment by myrdd** [comment] 2016-08-12 18:43
duplicate of #687

**Closed by myrdd** 2016-08-12 18:43 UTC
Labels: bug
