### ISSUE TITLE
Feature Request: Give option to use original RequestPolicy UI

### ISSUE THREAD

**Issue by simonsaysforcepush** [RequestPolicyContinued/requestpolicy#864] opened 2017-11-14 23:40 UTC
I've recently switched to RequestPolicy Continued from the original RequestPolicy, and honestly I can't stand it. There are a few things that make this version much less user-friendly than the old version:

1. Doesn't automatically refresh when you've allowed permissions
    - This was a great feature. I didn't have to manually refresh every time in order to see if a particula request was the issue.  

2. Context menu layout is bright and hard to read.
    - One of the great things about the old version was that it relied on my GTK theme. This doesn't seem to do that. I have vision issues, and really can't stand to see colors on a white background, not to mention that the layout is completely different. I know that technically this a completely different extension, but frankly I don't understand why these drastic UI changes occurred or were necessary.

At the very least, isn't there a way to have a "night mode" so that I'm not blinded every time I want to allow or deny a request? And can't it be fixed so that things automatically refresh?

Lastly, previously when I had allowed requests from google.com, any time I copied a link it copied the actual URL and not the google redirect URL... can this be re-added?

**Comment by myrdd** [comment] 2017-11-15 14:46
Hi,

> automatically refresh when you've allowed permissions

It should work: 

![screenshot 1](https://user-images.githubusercontent.com/4286829/32840539-3d7fee38-ca18-11e7-9577-34ad5dab65a6.png)

> One of the great things about the old version was that it relied on my GTK theme

There's an issue to bring it back: https://github.com/RequestPolicyContinued/requestpolicy/issues/662

> a way to have a "night mode"

I'm currently working on the WebExtension transition, so I don't have enough time to add a night mode. However, you can create your own style by creating a [`UserChrome.css`](http://kb.mozillazine.org/UserChrome.css) file. I've created this template for you: https://gist.github.com/myrdd/839d2ad675399be8b0d2d704dab6ab70

I did not test it, but you should be able to create your own color theme. It would be great if you could share your result with us (at least with a screenshot). :)

> Lastly, previously when I had allowed requests from google.com, any time I copied a link it copied the actual URL and not the google redirect URL

Not sure if I understand you correctly. Are you saying that—in the following example—you want to see `https://www.test.de/` (i.e. the destination url) in the address bar?

![screenshot 2](https://user-images.githubusercontent.com/4286829/32841740-6ed95d0e-ca1b-11e7-91f8-45a81084892c.png)

Imho the current behavior is better, because the site did not change yet. However, you could request for a feature to *copy* the destination url to the clipboard. But please wait until the WebExtension version of RP is released, because it will bring changes to the Redirection Notification UI. Please follow https://github.com/RequestPolicyContinued/requestpolicy/issues/863 if interested.

---

If you want this issue to be dedicated to creating an option to choose the menu UI theme, please rename the issue accordingly. :)

**Comment by simonsaysforcepush** [comment] 2017-11-15 19:53
@myrdd thank you very much for your reply. I have the refresh option enabled, but it doesn't seem to work, same goes for if I click "allow" after clicking a link. I'm using Firefox-ESR 52.4.1 (64-bit). I will wait to put the request for copying the link until after the webext version is complete, because that's definitely something I need. (I often help people trouble-shoot, and want to be able to copy links directly from google).

Let me know what info I can provide, or if I should open a new bug report about the redirect issue.

Thanks for all your hard work on this! I realized after re-reading that my tone was a bit more harsh than I intended.

**Comment by myrdd** [comment] 2017-11-16 09:55
> I have the refresh option enabled, but it doesn't seem to work, same goes for if I click "allow" after clicking a link. I'm using Firefox-ESR 52.4.1 (64-bit).

Sounds like you're using an old version—are you? The current version is `1.0.beta13.1`. Otherwise, please report the bug in a new issue. Remember to provide reproduction steps.

> I will wait to put the request for copying the link until after the webext version is complete, because that's definitely something I need.

Okay. You could, for example, request a keyboard shortcut for copying the destination url to the clipboard. I'm quite sure I'll keep with my opinion that the address bar should always show the *current* url.

> Thanks for all your hard work on this! I realized after re-reading that my tone was a bit more harsh than I intended.

You're welcome! No worries, that happens to me as well. ;)

> Let me know what info I can provide, or if I should open a new bug report about the redirect issue.

If you want to request "themes" for the new-style (1.0) RP menu, then please create a new issue. If you want the 0.5-style menu back, then follow/upvote https://github.com/RequestPolicyContinued/requestpolicy/issues/662. I'm closing this issue, since all mentioned (sub-)issues should be handled elsewhere.

**Closed by myrdd** 2017-11-16 09:55 UTC
Labels: type: user story
