### ISSUE TITLE
No way to import

### ISSUE THREAD

**Issue by jimbo1qaz** [RequestPolicyContinued/requestpolicy#581] opened 2015-01-25 04:33 UTC
No way to import policies at all.
No auto import.
No manual import from rule text file.
Contrary to several places where it is claimed that it auto-imports.

1.0.beta8.1

**Comment by myrdd** [comment] 2015-01-25 11:12
duplicate of #342. see also #354.

**Closed by myrdd** 2015-01-25 11:12 UTC
Labels: duplicate
